kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-0
  labels:
    name: pv-0
    type: local
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pv0"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-1
  labels:
    name: pv-1
    type: local
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pv1"
